version: "3.3"

services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: development
    environment:
      - NODE_ENV=development
    volumes:
      - ".:/code"
      # mount modules from image
      - "/code/node_modules"
    ports:
      - "4000:4000"
    command: "yarn watch"
